#!/usr/bin/env bash
# Push the release branch and open a release PR.
#
# Run after `pnpm release:prepare` has produced the chore(release) commit
# + manifest on a release-prep branch.
#
# After PR merges:
#   - The release-tags.yml workflow auto-creates per-package tags
#   - Each tag push triggers release.yml which publishes via npm OIDC

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ]; then
  echo "error: cannot open release PR from main." >&2
  exit 1
fi

MANIFEST=.release/manifest.json
if [ ! -f "$MANIFEST" ]; then
  echo "error: $MANIFEST not found. Run 'pnpm release:prepare' first." >&2
  exit 1
fi

# Push branch.
echo "→ pushing $BRANCH"
git push -u origin "$BRANCH"

# Build PR title + body from manifest.
TITLE_TAGS=$(jq -r '[.releases[] | "\(.package | split("/")[1])@\(.version)"] | join(", ")' "$MANIFEST")
TITLE="chore(release): publish $TITLE_TAGS"

BODY=$(cat <<EOF
## Release

This PR was generated by \`pnpm release:prepare\`. After merge, the
\`release-tags.yml\` workflow will create per-package tags from
\`.release/manifest.json\`, which in turn triggers \`release.yml\` to publish
each package to npm via OIDC Trusted Publishing.

### Packages

$(jq -r '.releases[] | "- **\(.package)** → \(.version)"' "$MANIFEST")

### Manifest

\`\`\`json
$(cat "$MANIFEST")
\`\`\`

### Merge

Use **rebase merge**. The chore(release) commit must land on main as-is so
the workflow can detect it via the head-commit message subject.

🤖 Generated by \`pnpm release:prepare\`.
EOF
)

echo "→ opening PR"
gh pr create --title "$TITLE" --body "$BODY"
