#!/usr/bin/env bash
# Push the release branch and open a release PR.
#
# CI only: the Scheduled Release workflow runs it after
# scripts/release/prepare.sh has produced the chore(release) commit +
# manifest on a release branch.
#
# After PR merges:
#   - The release-tags.yml workflow auto-creates per-package tags
#   - Each tag push triggers release.yml which publishes via npm OIDC

set -euo pipefail

if [ "${GITHUB_ACTIONS:-}" != "true" ]; then
  echo "error: release PRs are opened only by the Scheduled Release workflow." >&2
  exit 1
fi

cd "$(git rev-parse --show-toplevel)"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ]; then
  echo "error: cannot open release PR from main." >&2
  exit 1
fi

MANIFEST=.release/manifest.json
if [ ! -f "$MANIFEST" ]; then
  echo "error: $MANIFEST not found. Run scripts/release/prepare.sh first." >&2
  exit 1
fi

# Push branch.
echo "→ pushing $BRANCH"
git push -u origin "$BRANCH"

# Build PR title + body from manifest.
TITLE_TAGS=$(jq -r '[.releases[] | "\(.package | split("/")[1])@\(.version)"] | join(", ")' "$MANIFEST")
TITLE="chore(release): publish $TITLE_TAGS"

BODY=$(cat <<EOF
## Release

This PR was generated by the Scheduled Release workflow. After merge, the
\`release-tags.yml\` workflow will create per-package tags from
\`.release/manifest.json\`, which in turn triggers \`release.yml\` to publish
each package to npm via OIDC Trusted Publishing.

### Packages

$(jq -r '.releases[] | "- **\(.package)** → \(.version)"' "$MANIFEST")

### Manifest

\`\`\`json
$(cat "$MANIFEST")
\`\`\`

### Merge

Prepared from main at \`$(jq -r '.baseSha' "$MANIFEST")\`. Merge (squash keeps the
\`chore(release): publish\` subject Release Tags looks for) only while main is
still at that commit: CI fails this PR once main moves, and Release Tags
refuses to tag a release that merged onto a later main. If main has moved,
close this PR and re-run the Scheduled Release workflow.

🤖 Generated by the Scheduled Release workflow.
EOF
)

# Use REST directly. `gh pr create` uses GraphQL (5000 points/hour, easy
# to exhaust during an active release/debug session); REST shares the
# 5000-req/hour core bucket and is rarely the bottleneck.
REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
echo "→ opening PR via REST against $REPO"
PR_URL=$(jq -n \
  --arg title "$TITLE" \
  --arg head "$BRANCH" \
  --arg base "main" \
  --arg body "$BODY" \
  '{title: $title, head: $head, base: $base, body: $body}' \
  | gh api -X POST "/repos/$REPO/pulls" --input - --jq '.html_url')

echo "$PR_URL"
