/**
 * AdaptiveWorX™ Flow
 * Copyright (c) 2023-2026 Adaptive Intelligence, LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { describe, expect, it } from "vitest";
import type { CloudProvider, StackContext } from "../types/core.js";
import { exportStackReadme, generateStackReadme } from "./stack-readme.js";

describe("stack-readme", () => {
  const baseContext: StackContext = {
    org: "adaptiveworx",
    tenant: "worx",
    cloud: "aws",
    accountPurpose: "ops",
    stackPurpose: "iam",
    environment: "dev",
    region: "us-east-1",
    projectName: "worx-aws-dev",
    stackName: "ops-iam-use1",
  };

  describe("generateStackReadme", () => {
    it("should generate README with basic context", () => {
      const readme = generateStackReadme(baseContext);

      expect(readme).toContain("# adaptiveworx-aws-ops-iam-dev-us-east-1");
      expect(readme).toContain("## Stack Context");
      expect(readme).toContain("| Organization | adaptiveworx |");
      expect(readme).toContain("| Cloud | aws |");
      expect(readme).toContain("| Account Purpose | ops |");
      expect(readme).toContain("| Stack Purpose | iam |");
      expect(readme).toContain("| Environment | dev |");
      expect(readme).toContain("| Region | us-east-1 |");
      expect(readme).toContain("| Project Name | worx-aws-dev |");
      expect(readme).toContain("| Stack Name | ops-iam-use1 |");
      expect(readme).toContain("*Generated by Pulumi IaC*");
    });

    it("should include targetEnvironment when present", () => {
      const context: StackContext = {
        ...baseContext,
        targetEnvironment: "prd",
      };

      const readme = generateStackReadme(context);
      expect(readme).toContain("| Target Environment | prd |");
    });

    it("should not include targetEnvironment when undefined", () => {
      const readme = generateStackReadme(baseContext);
      expect(readme).not.toContain("| Target Environment |");
    });

    it("should not include targetEnvironment when empty string", () => {
      const context: StackContext = {
        ...baseContext,
        targetEnvironment: "",
      };

      const readme = generateStackReadme(context);
      expect(readme).not.toContain("| Target Environment |");
    });

    it("should include concern when present", () => {
      const context: StackContext = {
        ...baseContext,
        concern: "github",
        stackName: "ops-iam-github-use1",
      };

      const readme = generateStackReadme(context);
      expect(readme).toContain("| Stack Name | ops-iam-github-use1 |");
    });

    it("should handle empty options object", () => {
      const readme = generateStackReadme(baseContext, {});
      expect(readme).toContain("## Stack Context");
      expect(readme).not.toContain("## Custom Section");
    });

    it("should include additional sections", () => {
      const options = {
        additionalSections: {
          "Deployment Notes": "This stack manages IAM roles for GitHub Actions OIDC.",
          Dependencies: "- Requires GitHub OIDC provider\n- Cross-account trust policy",
        },
      };

      const readme = generateStackReadme(baseContext, options);
      expect(readme).toContain("## Deployment Notes");
      expect(readme).toContain("This stack manages IAM roles for GitHub Actions OIDC.");
      expect(readme).toContain("## Dependencies");
      expect(readme).toContain("- Requires GitHub OIDC provider");
    });

    it("should handle multiple additional sections in order", () => {
      const options = {
        additionalSections: {
          "Section 1": "Content 1",
          "Section 2": "Content 2",
          "Section 3": "Content 3",
        },
      };

      const readme = generateStackReadme(baseContext, options);
      const section1Index = readme.indexOf("## Section 1");
      const section2Index = readme.indexOf("## Section 2");
      const section3Index = readme.indexOf("## Section 3");

      expect(section1Index).toBeGreaterThan(0);
      expect(section2Index).toBeGreaterThan(section1Index);
      expect(section3Index).toBeGreaterThan(section2Index);
    });

    it("should handle additional sections with empty content", () => {
      const options = {
        additionalSections: {
          "Empty Section": "",
        },
      };

      const readme = generateStackReadme(baseContext, options);
      expect(readme).toContain("## Empty Section");
    });

    it("should format markdown correctly", () => {
      const readme = generateStackReadme(baseContext);

      // Check table formatting
      expect(readme).toContain("| Property | Value |");
      expect(readme).toContain("|----------|-------|");

      // Check footer
      expect(readme).toContain("---");
      expect(readme).toContain("*Generated by Pulumi IaC*");
    });

    it("should handle production environment", () => {
      const context: StackContext = {
        ...baseContext,
        environment: "prd",
        projectName: "worx-aws-prd",
      };

      const readme = generateStackReadme(context);
      expect(readme).toContain("| Environment | prd |");
      expect(readme).toContain("| Project Name | worx-aws-prd |");
    });

    it("should handle security environment with centralized VPC", () => {
      const context: StackContext = {
        ...baseContext,
        environment: "sec",
        accountPurpose: "ops",
        stackPurpose: "vpc",
        targetEnvironment: "dev",
        projectName: "worx-aws-sec",
        stackName: "dev-ops-vpc-use1",
      };

      const readme = generateStackReadme(context);
      expect(readme).toContain("| Environment | sec |");
      expect(readme).toContain("| Target Environment | dev |");
      expect(readme).toContain("| Stack Purpose | vpc |");
    });

    it("should handle all cloud providers", () => {
      const clouds: CloudProvider[] = ["aws", "azure", "gcp", "cloudflare"];

      for (const cloud of clouds) {
        const context: StackContext = {
          ...baseContext,
          cloud,
        };

        const readme = generateStackReadme(context);
        expect(readme).toContain(`| Cloud | ${cloud} |`);
      }
    });

    it("should handle all environment types", () => {
      const environments = ["dev", "stg", "prd", "sec"] as const;

      for (const environment of environments) {
        const context: StackContext = {
          ...baseContext,
          environment,
        };

        const readme = generateStackReadme(context);
        expect(readme).toContain(`| Environment | ${environment} |`);
      }
    });

    it("should handle care tenant", () => {
      const context: StackContext = {
        ...baseContext,
        tenant: "care",
        projectName: "care-aws-dev",
      };

      const readme = generateStackReadme(context);
      expect(readme).toContain("| Project Name | care-aws-dev |");
    });
  });

  describe("exportStackReadme", () => {
    it("should return object with readme property", () => {
      const result = exportStackReadme(baseContext);

      expect(result).toHaveProperty("readme");
      expect(typeof result.readme).toBe("string");
    });

    it("should generate same content as generateStackReadme", () => {
      const directReadme = generateStackReadme(baseContext);
      const exportedReadme = exportStackReadme(baseContext).readme;

      expect(exportedReadme).toBe(directReadme);
    });

    it("should pass options through to generateStackReadme", () => {
      const options = {
        additionalSections: {
          "Test Section": "Test content",
        },
      };

      const result = exportStackReadme(baseContext, options);
      expect(result.readme).toContain("## Test Section");
      expect(result.readme).toContain("Test content");
    });

    it("should work with empty options", () => {
      const result = exportStackReadme(baseContext, {});
      expect(result.readme).toContain("## Stack Context");
    });

    it("should work with no options parameter", () => {
      const result = exportStackReadme(baseContext);
      expect(result.readme).toContain("## Stack Context");
    });
  });
});
