/**
 * AdaptiveWorX™ Flow
 * Copyright (c) 2023-2026 Adaptive Intelligence, LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Stack README generation utilities for Pulumi Cloud
 * Auto-generates documentation that appears on stack pages
 */

import type * as pulumi from "@pulumi/pulumi";
import type { StackContext } from "../types/core.js";

export interface StackReadmeOptions {
  readonly outputs?: Record<string, pulumi.Output<unknown>>;
  readonly additionalSections?: Record<string, string>;
}

/**
 * Generates a formatted README for Pulumi Cloud stack page
 */
export function generateStackReadme(
  context: StackContext,
  options: StackReadmeOptions = {}
): string {
  const { additionalSections = {} } = options;

  let readme = `# ${context.org}-${context.cloud}-${context.accountPurpose}-${context.stackPurpose}-${context.environment}-${context.region}\n\n`;

  // Stack Context Table
  readme += "## Stack Context\n\n";
  readme += "| Property | Value |\n";
  readme += "|----------|-------|\n";
  readme += `| Organization | ${context.org} |\n`;
  readme += `| Cloud | ${context.cloud} |\n`;
  readme += `| Account Purpose | ${context.accountPurpose} |\n`;
  readme += `| Stack Purpose | ${context.stackPurpose} |\n`;
  readme += `| Environment | ${context.environment} |\n`;
  readme += `| Region | ${context.region} |\n`;
  readme += `| Project Name | ${context.projectName} |\n`;
  readme += `| Stack Name | ${context.stackName} |\n`;
  if (context.targetEnvironment !== undefined && context.targetEnvironment.length > 0) {
    readme += `| Target Environment | ${context.targetEnvironment} |\n`;
  }
  readme += "\n";

  // Additional Sections
  for (const [sectionTitle, sectionContent] of Object.entries(additionalSections)) {
    readme += `## ${sectionTitle}\n\n${sectionContent}\n\n`;
  }

  // Footer
  readme += "---\n";
  readme += "*Generated by Pulumi IaC*\n";

  return readme;
}

/**
 * Export stack README for Pulumi Cloud
 * Returns an object with readme property to be merged into stack outputs
 */
export function exportStackReadme(
  context: StackContext,
  options: StackReadmeOptions = {}
): { readme: string } {
  const readme = generateStackReadme(context, options);
  return { readme };
}
